language: rust

rust:
  - 1.18.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

dist: trusty
sudo: false

addons:
  apt:
    packages:
      - libappindicator3-dev
      - libgtk-3-dev

cache: cargo

install:
  - (cargo install rustfmt || true)
  - PATH=$PATH:/home/travis/.cargo/bin

script:
  - cargo fmt -- --write-mode=diff
  - cargo build --verbose
  - cargo test --verbose
